### ISSUE TITLE
Remove or Hide Like button

### ISSUE THREAD

**Issue by silasmeredith** [DevProgress/swear-jar#12]
We don't have a Facebook page, so we shouldn't have a Like button yet.

**Comment by jjandoc** [comment]
Is this an issue? The button used is for liking a URL, not a FB page.

**Comment by silasmeredith** [comment]
Hmmmm, this is new to me. The button asks you to log into Facebook; is there some way to like a URL through Facebook? Once you log in , the window just closes.

**Comment by jjandoc** [comment]
That's how the Like button has always worked, long before FB pages were created. You log in so that your FB activity of liking a URL has been recorded, then the like button widget increments up by one.

**Comment by jjandoc** [comment]
Per discussion in another thread, removing.

**Comment by jjandoc** [comment]
Fixed in #29
