### ISSUE TITLE
Add a counter to the main page, for users to see

### ISSUE THREAD

**Issue by silasmeredith** [DevProgress/swear-jar#15]
Count the number of people who have pledged.

**Comment by JaneRuby** [comment]
![option1](https://cloud.githubusercontent.com/assets/19919252/19421159/d28379ea-93bf-11e6-867d-4d27c1131407.png)
![option2](https://cloud.githubusercontent.com/assets/19919252/19421160/d28f76fa-93bf-11e6-9dca-371688f6f971.png)

two possible ideas for the pledge counter, i was more focused on placement, than copy content. Willing to come up with other options too :)

**Comment by jmithani** [comment]
For copy, how about "Join ___ pledges" ?

**Comment by jmithani** [comment]
Or "___ pledges and counting!" I feel like shorter might be better in this case. Thoughts?

**Comment by JaneRuby** [comment]
yeah whatever for that, I was more focused on location. My fav is the first one where it's right over his head. lol

**Comment by JaneRuby** [comment]
![version4](https://cloud.githubusercontent.com/assets/19919252/19424102/1eea2e88-93ec-11e6-8755-0b2a68eba579.png)
![verison1](https://cloud.githubusercontent.com/assets/19919252/19424104/1eedffae-93ec-11e6-892a-786c5f712efa.png)
![version2](https://cloud.githubusercontent.com/assets/19919252/19424101/1eea331a-93ec-11e6-82be-81f162417f6b.png)
![version3](https://cloud.githubusercontent.com/assets/19919252/19424103/1eecd868-93ec-11e6-8020-f0659909f4be.png)

new edits for the counter. Some more cheeky than others. the pledge counter icon is totally movable so wherever works for me, I can send someone the PSD file.

**Comment by ldworkin** [comment]
done!
