### ISSUE TITLE
Background image not appearing on Android 7.0, Firefox browser

### ISSUE THREAD

**Issue by silasmeredith** [DevProgress/swear-jar#20]

**Comment by jjandoc** [comment]
I don't have access to a physical android at the moment so can't reproduce. I did check in BrowserStack in Chrome and this looks fine to me. I've also deployed the most up-to-date design changes that are in master. @silasmeredith, can you check this again and see if this is still something you can reproduce?

**Comment by jjandoc** [comment]
Tested by garrett who said it was all good. Let me know if you still see this bug.
