### ISSUE TITLE
Design update

### ISSUE THREAD

**Issue by silasmeredith** [DevProgress/swear-jar#21]
First: @jmithani  will update the mockups to account for different screen sizes.

Second: we'll mark this as "Help Wanted" and a developer can implement the changes.

**Comment by jmithani** [comment]
Here is the link to the new mockups: https://devprogress.slack.com/files/jasmine/F2KVCG84A/quarter-mocks.zip

I'll go ahead and add labels asking for help!

**Comment by silasmeredith** [comment]
Thanks, @jmithani ! Marked as "Help wanted," so anyone who can implement this, please take the ticket! 

I do think we should take "the fuck" out of "Sign me the fuck up!" I think it's funny, but not everyone will, and the site is pretty fun as an understated statement.

**Comment by JaneRuby** [comment]
![design-revisions-option](https://cloud.githubusercontent.com/assets/19919252/19139702/6ea2fa20-8b4c-11e6-8f91-c102d810abe1.jpg)

**Comment by JaneRuby** [comment]
![revision-2](https://cloud.githubusercontent.com/assets/19919252/19139719/849113e4-8b4c-11e6-995c-252196acd770.jpg)

I centered this image on this one and tweaked the color more to the original

**Comment by jmithani** [comment]
The colors are #215BAA for dark blue and #03A9E0 for light blue, which I snagged off of the i-like-hillary-but UI redesign. @JaneRuby did you have any feedback on the mobile mock?

**Comment by JaneRuby** [comment]
![quarter-mobile-mock](https://cloud.githubusercontent.com/assets/19919252/19169242/253885f2-8bd9-11e6-9d45-acf454e9c578.jpg)
I just reversed the image back and altered it slightly with coloring to match the other mock-up (and also differentiate from the original :P).

I think the title font should fill the space more, maybe make a tiny bit smaller to fill the space.

**Comment by JaneRuby** [comment]
i can do more later tonight and format images, etc, whatever is needed!

**Comment by jjandoc** [comment]
I'll work on development for this.

**Comment by jjandoc** [comment]
So not sure who owns the final say in design here, but I can implement that tonight. I made a lot of updates last night so I recommend pulling down the `feature/design-update` branch and seeing where we're at. It'd be great to get a psd or sketch file with final design mocks and final say on copy and whether or not to use FB share/like widget as there are a few other outstanding issues that I can knock out while updating the page.

**Comment by JaneRuby** [comment]
@jjandoc I can upload a psd file if you need, since I have the most recent edits. Not sure where we stand on FB share buttons, etc. @silasmeredith please advise on the widget situation?

**Comment by silasmeredith** [comment]
As far as Facebook integration is concerned: there's really one thing we want them to do, which is to share this on Facebook. Let's keep it simple and focused on that. Let's stick with one single button, that has on it the Facebook logo and the word "Share."

@jjandoc : I'm a real GitHub beginner. Happy to look at the most recent implementation, but I don't know how to "pull down the feature/design-update branch." Is that something that someone with no GitHub experience and no specialized software can do?

Broadly speaking, I like the most recent mockups that @JaneRuby, based on her and @jmithani 's work. Most copy changes have their own open tickets.

**Comment by jjandoc** [comment]
@silasmeredith I'm happy to walk you through the easy way to get started with Github and building the branch if you've got 15 minutes and want to screen share. Hit me up on Slack if we're both online.

But from speaking with @JaneRuby directly it looks like we're good with where _design_ is right now. Content and features can be worked out in other. PR #28 should close this out.
