### ISSUE TITLE
Email validator is wrong

### ISSUE THREAD

**Issue by AaronSofaer** [DevProgress/swear-jar#5]
The email validator considers aaronsofaer+asdfasdf@gmail.com invalid, which is incorrect; that is a valid email address.

**Comment by jjandoc** [comment]
So the original code used a regex test to validate an email. In my last PR, I dropped in native  browser HTML5 validation on top of this which works for all modern browsers except Safari. The pre-existing regex test acts as a redundancy. There's a few different options here.
1. We can revise the regex. Suggestions are here: http://emailregex.com/. There is a lot of discussion (see the bottom of the page) about whether these regex tests are or are not appropriate.
2. Drop the regex and rely solely on browser validation. The con is that this doesn't validate on Safari.
3. Keep browser validation, drop the regex. For Safari, rely on very simple validation by checking if value is non-empty and/or passes a very basic `/.+@.+/` test.

Third option is my recommendation.

**Comment by AaronSofaer** [comment]
Third option it is.
