### ISSUE TITLE
Modify site and DB "schema" to allow multiple causes, range of pledge values

### ISSUE THREAD

**Issue by AaronSofaer** [DevProgress/swear-jar#53]
A user should be able to pledge for two different causes (one for every time Trump tweets, one for every time he interrupts Clinton at the next debate).

A user should be able to set the amount they pledge for.

Firebase data needs to then be "migrated" to whatever new pattern is used.

**Comment by jmithani** [comment]
Here is the drop-down mocks I made: https://files.slack.com/files-pri/T1AJ4F4KC-F2Q40VASJ/download/drop-down_png.zip

Does not include changing the amount they want to pledge, just selecting which trigger to pledge for.

**Comment by JaneRuby** [comment]
@ldworkin 
![down-arrow copy](https://cloud.githubusercontent.com/assets/19919252/19477867/c473505e-9505-11e6-9eed-ceb790b2215b.png)
